name: Unpack Unity VCS installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-exe:
    runs-on: windows-latest

    steps:
      - name: Download installer
        run: |
          $version = "11.0.16.8622"
          $link = "https://www.plasticscm.com/download/downloadinstaller/$version/plasticscm/windows/full?flags=None"
          (New-Object Net.WebClient).DownloadFile($link, ".\installer.exe")

      - name: Run installer
        run: |
          mkdir -p installed
          .\installer.exe --mode unattended --unattendedmodeui none --prefix "$(pwd)\installed" --debuglevel 4 --debugtrace "(pwd)\log.txt"

          $required = @('client','server','theme','install.properties')

          while($True)
          {
            $items = Get-ChildItem installed | Foreach-Object {$_.name}
            $itemsLeft = ($required.Where{$_ -notin $items})
            if($itemsLeft.Count -eq 0)
            {
              break;
            }

            Write-Output "Items left - $itemsLeft"
            Start-Sleep -Seconds 1
          }

          Write-Host "Installation completed"

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          cp -r .\installed\client artifacts\
          cp -r .\installed\theme artifacts\
          cp -r .\installed\install.properties artifacts\
          Compress-Archive -Path .\artifacts\ -DestinationPath release-files.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-files.zip
          asset_name: release-files.zip
          asset_content_type: application/zip
