name: Unpack Unity VCS installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-exe:
    runs-on: windows-latest

    steps:
      - name: Download installer
        run: |
          $version = "11.0.16.8622"
          $link = "https://www.plasticscm.com/download/downloadinstaller/$version/plasticscm/windows/full?flags=None"
          (New-Object Net.WebClient).DownloadFile($link, ".\installer.exe")

      - name: Run installer
        run: |
          mkdir -p installed
          installer.exe --mode unattended --prefix "installed"

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          cp installed\client artifacts\
          cp installed\theme artifacts\

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: unityvcs-artifacts
          path: artifacts/
