name: Unpack Unity VCS installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-exe:
    runs-on: windows-latest

    steps:
      - name: Download installer
        run: |
          write-host "test"

      - name: Run installer
        run: |
          write-host "Running installer"

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          touch artifacts/test.txt

      - name: Upload
        uses: actions/upload-artifacts@v3
        with:
          name: unityvcs-artifacts
          path: artifacts/
